# Generated by Django 3.1.6 on 2021-04-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20210402_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ManyToManyField(blank=True, related_name='posts', to='network.Post'),
        ),
    ]
