# Generated by Django 3.1.6 on 2021-04-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_post_likes_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes_count',
        ),
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ManyToManyField(blank=True, related_name='likes', to='network.Post'),
        ),
    ]
